import {
    AlertCircle, AlertOctagon, AlertTrianle, Bell, Bookmark, Copy, Eye, EyeOff, File, FileText, Filter, FullScreenEnter, FullScreenExit, Maximize, Menu, MicOff, Minus, MinusCircle, MoreHorizontal, MunusSquire, Plus, PlusSquire,
    Move,
    Crop,
    BellOff,
    PlusCircle,
    PlayCircle,
    Check,
    RotageCW,
    CheckSquire,
    Play,
    Search,
    Repeat,
    DownloadCloude,
    Setting,
    Download,
    Globe,
    Login,
    QrCode,
    RotateCcw,
    Close,
    Refresh,
    ExternalLink,
    CheckCircle,
    Clipboard,
    Logout,
    HelpCircle,
    ShoppingCart,
    Save,
    Info,
    Home,
    Share,
    Heart,
    Trash,
    Export,
    Hash,
    Edit,
    ThumbsDown,
    ThumbsUp,
    Tag,
    Unlock,
    Traget,
    TrendingUp,
    TrendingDown,
    UploadCloud,
    Pause,
    Slider,
    Slash,
    Star,
    StopCircle,
    PauseCircle,
    Link,
    List,
    Zap,
    Shuffle,
    Lock,
    AlignJustify,
    AlertOnly,
    ZoomIn,
    ZoomOut,
    XCircle,
    XSquire,
    Upload,
    AlignRight,
    AlignLeft,
    AlignCenter,
    Anchor,
    Attachment,
    Bold,
    Delete,
    EditInline,
    EditCompose,
    FilePlus,
    FileMinus,
    Grid,
    Folder,
    Flag,
    Type,
    Minimize,
    Italic,
    Image,
    FileZip,
    Underline,
    Film,
    AirPlay,
    AtSign,
    Blutooth,
    Camera,
    CameraOff,
    Cast,
    Inbox,
    Mail,
    MessageCircle,
    MessageSquire,
    Mic,
    PhoneCall,
    Phone,
    PhoneOutgoing,
    PhoneOff,
    PhoneMissed,
    PhoneIncoming,
    PhoneForwarded,
    Send,
    MailOpen,
    Video,
    VideoOff,
    VoiceMail,
    Droplet,
    Disc,
    CrossShair,
    Circle,
    Chrome,
    Briefcase,
    Box,
    Book,
    WifiOff,
    Wifi,
    Layers,
    Layout,
    Sidebar,
    Squire,
    Triangle,
    LifeBoy,
    Loader,
    Octagon,
    Package,
    Percent,
    ArrowUpLeft,
    Wind,
    Ticket,
    Dot,
    MenuDots,
    Stamp,
    Bill,
    Coins,
    Appstore,
    Announcement,
    Sheild,
    ChevronUp,
    ArrowUpRight,
    ArrowLeft,
    ArrowUp,
    ArrowDownRight,
    ArrowDownLeft,
    ArrowDown,
    ArrowRight,
    ChevronsRight,
    ChevronsLeft,
    ChevronsDown,
    ChevronsUp,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    Cloud,
    Clock,
    Calendar,
    VolumeHigh,
    VolumeLow,
    VolumeMute,
    Volume,
    SkipForward,
    Skipback,
    Rewind,
    Headphone,
    FastFroward,
    CornerLeftDown,
    CornerUpLeft,
    CornerDownRight,
    CornerLeftUp,
    CornerRightDown,
    CornerRightUp,
    CornerDownLeft,
    CornerUpRight,
    Cpu,
    Battery,
    BetterCharging,
    Users,
    UserMinus,
    UserPlus,
    UserX,
    User,
    UserCheck,
    Cloudrain,
    Watch,
    Sun,
    Sunrise,
    Sunset,
    Moon,
    CloudLighting,
    CloudeOff,
    CloudeSnow,
    CloudDrizzle,
    History,
    Codepen,
    Tv,
    Thermometer,
    Tablet,
    Speaker,
    Smartphone,
    Server,
    Radio,
    Monitor,
    Printer,
    BarChartAlt,
    Activity,
    Twitter,
    Slack,
    Pocket,
    Instagram,
    Hithub,
    Gitlab,
    Resizer,
    Ruppes,
    Dollar,
    CreditCard,
    Navigation,
    MapPin,
    Compass,
    Map,
    BarChart,
    PaiChart,
    Facebook,
} from 'jiffy-icons'
export  const componentsArray = [
    { compName: AlertCircle, description: "Alert Circle" },
    { compName: AlertOctagon, description: "Alert Octagon" },
    { compName: AlertTrianle, description: "Alert Triangle" },
    { compName: Bell, description: "Bell" },
    { compName: Bookmark, description: "Bookmark" },
    { compName: Copy, description: "Copy" },
    { compName: Eye, description: "Eye" },
    { compName: EyeOff, description: "Eye Off" },
    { compName: File, description: "File" },
    { compName: FileText, description: "File Text" },
    { compName: Filter, description: "Filter" },
    { compName: FullScreenEnter, description: "Full Screen Enter" },
    { compName: FullScreenExit, description: "Full Screen Exit" },
    { compName: Maximize, description: "Maximize" },
    { compName: Menu, description: "Menu" },
    { compName: MicOff, description: "Mic Off" },
    { compName: Minus, description: "Minus" },
    { compName: MinusCircle, description: "Minus Circle" },
    { compName: MoreHorizontal, description: "More Horizontal" },
    { compName: MunusSquire, description: "Minus Square" },
    { compName: Plus, description: "Plus" },
    { compName: PlusSquire, description: "Plus Square" },
    { compName: Move, description: "Move" },
    { compName: Crop, description: "Crop" },
    { compName: BellOff, description: "Bell Off" },
    { compName: PlusCircle, description: "Plus Circle" },
    { compName: PlayCircle, description: "Play Circle" },
    { compName: Check, description: "Check" },
    { compName: RotageCW, description: "Rotate Clockwise" },
    { compName: CheckSquire, description: "Check Square" },
    { compName: Play, description: "Play" },
    { compName: Search, description: "Search" },
    { compName: Repeat, description: "Repeat" },
    { compName: DownloadCloude, description: "Download Cloud" },
    { compName: Setting, description: "Setting" },
    { compName: Download, description: "Download" },
    { compName: Globe, description: "Globe" },
    { compName: Login, description: "Login" },
    { compName: QrCode, description: "QR Code" },
    { compName: RotateCcw, description: "Rotate Counter Clockwise" },
    { compName: Close, description: "Close" },
    { compName: Refresh, description: "Refresh" },
    { compName: ExternalLink, description: "External Link" },
    { compName: CheckCircle, description: "Check Circle" },
    { compName: Clipboard, description: "Clipboard" },
    { compName: Logout, description: "Logout" },
    { compName: HelpCircle, description: "Help Circle" },
    { compName: ShoppingCart, description: "Shopping Cart" },
    { compName: Save, description: "Save" },
    { compName: Info, description: "Info" },
    { compName: Home, description: "Home" },
    { compName: Share, description: "Share" },
    { compName: Heart, description: "Heart" },
    { compName: Trash, description: "Trash" },
    { compName: Export, description: "Export" },
    { compName: Hash, description: "Hash" },
    { compName: Edit, description: "Edit" },
    { compName: ThumbsDown, description: "Thumbs Down" },
    { compName: ThumbsUp, description: "Thumbs Up" },
    { compName: Tag, description: "Tag" },
    { compName: Unlock, description: "Unlock" },
    { compName: Traget, description: "Target" },
    { compName: TrendingUp, description: "Trending Up" },
    { compName: TrendingDown, description: "Trending Down" },
    { compName: UploadCloud, description: "Upload Cloud" },
    { compName: Pause, description: "Pause" },
    { compName: Slider, description: "Slider" },
    { compName: Slash, description: "Slash" },
    { compName: Star, description: "Star" },
    { compName: StopCircle, description: "Stop Circle" },
    { compName: PauseCircle, description: "Pause Circle" },
    { compName: Link, description: "Link" },
    { compName: List, description: "List" },
    { compName: Zap, description: "Zap" },
    { compName: Shuffle, description: "Shuffle" },
    { compName: Lock, description: "Lock" },
    { compName: AlignJustify, description: "Align Justify" },
    { compName: AlertOnly, description: "Alert Only" },
    { compName: ZoomIn, description: "Zoom In" },
    { compName: ZoomOut, description: "Zoom Out" },
    { compName: XCircle, description: "X Circle" },
    { compName: XSquire, description: "X Square" },
    { compName: Upload, description: "Upload" },
    { compName: AlignRight, description: "Align Right" },
    { compName: AlignLeft, description: "Align Left" },
    { compName: AlignCenter, description: "Align Center" },
    { compName: Anchor, description: "Anchor" },
    { compName: Attachment, description: "Attachment" },
    { compName: Bold, description: "Bold" },
    { compName: Delete, description: "Delete" },
    { compName: EditInline, description: "Edit Inline" },
    { compName: EditCompose, description: "Edit Compose" },
    { compName: FilePlus, description: "File Plus" },
    { compName: FileMinus, description: "File Minus" },
    { compName: Grid, description: "Grid" },
    { compName: Folder, description: "Folder" },
    { compName: Flag, description: "Flag" },
    { compName: Type, description: "Type" },
    { compName: Minimize, description: "Minimize" },
    { compName: Italic, description: "Italic" },
    { compName: Image, description: "Image" },
    { compName: FileZip, description: "File Zip" },
    { compName: Underline, description: "Underline" },
    { compName: Film, description: "Film" },
    { compName: AirPlay, description: "AirPlay" },
    { compName: AtSign, description: "At Sign" },
    { compName: Blutooth, description: "Bluetooth" },
    { compName: Camera, description: "Camera" },
    { compName: CameraOff, description: "Camera Off" },
    { compName: Cast, description: "Cast" },
    { compName: Inbox, description: "Inbox" },
    { compName: Mail, description: "Mail" },
    { compName: MessageCircle, description: "Message Circle" },
    { compName: MessageSquire, description: "Message Square" },
    { compName: Mic, description: "Mic" },
    { compName: PhoneCall, description: "Phone Call" },
    { compName: Phone, description: "Phone" },
    { compName: PhoneOutgoing, description: "Phone Outgoing" },
    { compName: PhoneOff, description: "Phone Off" },
    { compName: PhoneMissed, description: "Phone Missed" },
    { compName: PhoneIncoming, description: "Phone Incoming" },
    { compName: PhoneForwarded, description: "Phone Forwarded" },
    { compName: Send, description: "Send" },
    { compName: MailOpen, description: "Mail Open" },
    { compName: Video, description: "Video" },
    { compName: VideoOff, description: "Video Off" },
    { compName: VoiceMail, description: "Voicemail" },
    { compName: Droplet, description: "Droplet" },
    { compName: Disc, description: "Disc" },
    { compName: CrossShair, description: "Crosshair" },
    { compName: Circle, description: "Circle" },
    { compName: Chrome, description: "Chrome" },
    { compName: Briefcase, description: "Briefcase" },
    { compName: Box, description: "Box" },
    { compName: Book, description: "Book" },
    { compName: WifiOff, description: "WiFi Off" },
    { compName: Wifi, description: "WiFi" },
    { compName: Layers, description: "Layers" },
    { compName: Layout, description: "Layout" },
    { compName: Sidebar, description: "Sidebar" },
    { compName: Squire, description: "Square" },
    { compName: Triangle, description: "Triangle" },
    { compName: LifeBoy, description: "Lifebuoy" },
    { compName: Loader, description: "Loader" },
    { compName: Octagon, description: "Octagon" },
    { compName: Package, description: "Package" },
    { compName: Percent, description: "Percent" },
    { compName: ArrowUpLeft, description: "Arrow Up Left" },
    { compName: Wind, description: "Wind" },
    { compName: Ticket, description: "Ticket" },
    { compName: Dot, description: "Dot" },
    { compName: MenuDots, description: "Menu Dots" },
    { compName: Stamp, description: "Stamp" },
    { compName: Bill, description: "Bill" },
    { compName: Coins, description: "Coins" },
    { compName: Appstore, description: "App Store" },
    { compName: Announcement, description: "Announcement" },
    { compName: Sheild, description: "Shield" },
    { compName: ChevronUp, description: "Chevron Up" },
    { compName: ArrowUpRight, description: "Arrow Up Right" },
    { compName: ArrowLeft, description: "Arrow Left" },
    { compName: ArrowUp, description: "Arrow Up" },
    { compName: ArrowDownRight, description: "Arrow Down Right" },
    { compName: ArrowDownLeft, description: "Arrow Down Left" },
    { compName: ArrowDown, description: "Arrow Down" },
    { compName: ArrowRight, description: "Arrow Right" },
    { compName: ChevronsRight, description: "Chevrons Right" },
    { compName: ChevronsLeft, description: "Chevrons Left" },
    { compName: ChevronsDown, description: "Chevrons Down" },
    { compName: ChevronsUp, description: "Chevrons Up" },
    { compName: ChevronRight, description: "Chevron Right" },
    { compName: ChevronLeft, description: "Chevron Left" },
    { compName: ChevronDown, description: "Chevron Down" },
    { compName: Cloud, description: "Cloud" },
    { compName: Clock, description: "Clock" },
    { compName: Calendar, description: "Calendar" },
    { compName: VolumeHigh, description: "Volume High" },
    { compName: VolumeLow, description: "Volume Low" },
    { compName: VolumeMute, description: "Volume Mute" },
    { compName: Volume, description: "Volume" },
    { compName: SkipForward, description: "Skip Forward" },
    { compName: Skipback, description: "Skip Back" },
    { compName: Rewind, description: "Rewind" },
    { compName: Headphone, description: "Headphone" },
    { compName: FastFroward, description: "Fast Forward" },
    { compName: CornerLeftDown, description: "Corner Left Down" },
    { compName: CornerUpLeft, description: "Corner Up Left" },
    { compName: CornerDownRight, description: "Corner Down Right" },
    { compName: CornerLeftUp, description: "Corner Left Up" },
    { compName: CornerRightDown, description: "Corner Right Down" },
    { compName: CornerRightUp, description: "Corner Right Up" },
    { compName: CornerDownLeft, description: "Corner Down Left" },
    { compName: CornerUpRight, description: "Corner Up Right" },
    { compName: Cpu, description: "CPU" },
    { compName: Battery, description: "Battery" },
    { compName: BetterCharging, description: "Better Charging" },
    { compName: Users, description: "Users" },
    { compName: UserMinus, description: "User Minus" },
    { compName: UserPlus, description: "User Plus" },
    { compName: UserX, description: "User X" },
    { compName: User, description: "User" },
    { compName: UserCheck, description: "User Check" },
    { compName: Cloudrain, description: "Cloud Rain" },
    { compName: Watch, description: "Watch" },
    { compName: Sun, description: "Sun" },
    { compName: Sunrise, description: "Sunrise" },
    { compName: Sunset, description: "Sunset" },
    { compName: Moon, description: "Moon" },
    { compName: CloudLighting, description: "Cloud Lightning" },
    { compName: CloudeOff, description: "Cloud Off" },
    { compName: CloudeSnow, description: "Cloud Snow" },
    { compName: CloudDrizzle, description: "Cloud Drizzle" },
    { compName: History, description: "History" },
    { compName: Codepen, description: "Codepen" },
    { compName: Tv, description: "TV" },
    { compName: Thermometer, description: "Thermometer" },
    { compName: Tablet, description: "Tablet" },
    { compName: Speaker, description: "Speaker" },
    { compName: Smartphone, description: "Smartphone" },
    { compName: Server, description: "Server" },
    { compName: Radio, description: "Radio" },
    { compName: Monitor, description: "Monitor" },
    { compName: Printer, description: "Printer" },
    { compName: BarChartAlt, description: "Bar Chart Alt" },
    { compName: Activity, description: "Activity" },
    { compName: Twitter, description: "Twitter" },
    { compName: Slack, description: "Slack" },
    { compName: Pocket, description: "Pocket" },
    { compName: Instagram, description: "Instagram" },
    { compName: Hithub, description: "Github" },
    { compName: Gitlab, description: "Gitlab" },
    { compName: Resizer, description: "Resizer" },
    { compName: Ruppes, description: "Rupees" },
    { compName: Dollar, description: "Dollar" },
    { compName: CreditCard, description: "Credit Card" },
    { compName: Navigation, description: "Navigation" },
    { compName: MapPin, description: "Map Pin" },
    { compName: Compass, description: "Compass" },
    { compName: Map, description: "Map" },
    { compName: BarChart, description: "Bar Chart" },
    { compName: PaiChart, description: "Pie Chart" },
    { compName: Facebook, description: "Facebook" }
];